dirs:
  data_dir: data
  model_dir: models
  config_dir: confgs
  raw_data_dir: data/raw
  processed_data_dir: data/processed
  artifacts_dir: artifacts

data_paths:
  raw_data_path: data/raw/weatherAUS.csv
  xg_processed_data_path: data\processed\xg_weatherAUS_processed.csv
  cleaned_data_path: data/processed/cleaned_data.csv
  test_data_path: data\processed\test_dataset.csv
   

artifacts_paths:
  xg_model_path: models/xgboost_model.pkl